name: uploader
description: A Dart script for uploading Android App Bundles to Google Play
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  test: ^1.24.3
  mockito: ^5.4.2
  build_runner: ^2.4.6

executables:
  uploader: